### ISSUE TITLE
Display related laws

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#159]
On every law's page, display a listing of similar laws. This has already been done via Solarium on Virginia Decoded, so it should be easy to implement.

The way to do this will be via a new Search class, with a `similar_laws()` method. Then, invoke that method within `Laws::get_law()`, and return the related laws data along with all other law data. Finally, display the related laws data on the sidebar of `law.php`.

**Comment by waldoj** [comment]
@krues8dr, what do you think about accomplishing this via MySQL? It seems too computationally demanding, or so it was when I tried to implement a feature like this in MySQL in, like, 2004.

**Comment by krues8dr** [comment]
MySQL by itself really isn't equipped to solve this problem, I think.  You can do fulltext search, Levenshtein distance, and other fun tricks - but since it lacks any internal sense of relevance (no central index), there's no great way to say that documents are "related".  The best it can do is find ones that are similar from a text standpoint - but that's expensive for whole-documents.  The best we could do is generate this data at import time based on our dictionary terms, and find anything that shares these terms.  Maybe use our thesaurus file for this too.  I'm struggling to think of anything more elegant here.  

I'll have a look at the solr schema and see if I can figure out what the original intent was here and if it's something doable.

**Comment by krues8dr** [comment]
Ok, this was [a bug with Solr < 4.6](https://issues.apache.org/jira/browse/SOLR-5368).  I've upgraded to 4.10 and now I'm getting back `moreLikeThis` values.  I'll implement this in the `SolrSearchEngine` now.

**Comment by waldoj** [comment]
Boy, am I glad to hear that. I thought I was losing my mind.

**Comment by krues8dr** [comment]
`The absence of evidence is not the evidence of absence.`  ;)

**Comment by waldoj** [comment]
Handling this in MySQL with dictionary terms are a good idea. Basically, use those as auto-generated tags. If the law contains more than X dictionary terms, and there are other laws that share more than Y% of those dictionary terms, then display the top Z of those, sorted by Y% DESC. Seems pretty doable, I think!

**Comment by krues8dr** [comment]
But the overhead here is painful, we'll have to cache this on import.  I'd say it's out of scope for a 1.0, since it's now working in Solr properly.

**Comment by waldoj** [comment]
Makes sense to me.
