### ISSUE TITLE
Create the functionality to add laws to a portfolio

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#30]
Let people maintain a sort of a shopping cart of laws (and chapters, titles, etc?).
- [ ] [create JavaScript functions](https://github.com/julien-maurel/jQuery-Storage-API) to add, remove, and display the status of an individual law in local storage
- [ ] create a JavaScript function to list every law in local storage
- [ ] implement the add/remove/status functionality on the law page
- [ ] create a new page to list every law in local storage
- [ ] devise a name for this feature
- [ ] display the menu item for this new page only if the user has 1+ laws in local storage

**Comment by krues8dr** [comment]
I'm reading more on localstorage and it sounds like it's just as impermanent as cookies:

>I can't speak for other platforms, but on my 4.1 Android device, I'm using localStorage to store some data locally with jQuery Mobile, and I've found that Android will clear my cache every week or so without my knowledge. 

http://stackoverflow.com/questions/7750857/how-permanent-is-local-storage-on-android-and-ios

I'm not sure this is a good way to implement this feature if it's so ephemeral.  Cookies have similar problems - we can try and make them "permanent", but it's not going to stick.  We really will have to document this if we're going to do it, because it's going to be losing people's data constantly.

**Comment by waldoj** [comment]
Yup. If people delete their local storage (not something people generally do accidentally) then, yes, they will lose their local storage. Short of an entire login and password system, there is nothing that will survive people deleting their cookies _or_ their local storage. :) I bet we could set an expiry date of 30 days, and it would _still_ work great for just about everybody. The traffic patterns that I see are people engaging in short bursts of research—anywhere from an hour to a week—and then they don't come back.

**Comment by krues8dr** [comment]
![screen shot 2017-01-18 at 2 43 31 pm](https://cloud.githubusercontent.com/assets/127904/22080209/b5c6cec6-dd8c-11e6-9ce1-b1cabb40e128.jpg)
![screen shot 2017-01-18 at 2 43 46 pm](https://cloud.githubusercontent.com/assets/127904/22080210/b5c79dce-dd8c-11e6-85a6-11b1a50bfd3f.jpg)

**Comment by waldoj** [comment]
Oooh, very nice! The pinned metaphor works well, too.
