### ISSUE TITLE
Trim section numbers

### ISSUE THREAD

**Issue by krues8dr** [statedecoded/statedecoded#589]
I need to verify that we're properly cleaning up text on import of XML files, so that section numbers are `trim()`med. Miami-Dade is reporting for [files like this](https://github.com/antoniorllanos/miamidecoded-xml/blob/master/%0A____________APPENDIX_A%0A__________ORDINANCES_CREATING_MUNICIPALITIES.xml) that urls aren't properly being generated. I've confirmed the url issue on their instance (image below) but I'm not sure if the code has been fixed since the version they're using.

![screen shot 2015-06-18 at 2 42 58 pm](https://cloud.githubusercontent.com/assets/127904/8239310/02c33166-15c9-11e5-8272-74abfe21c8b0.jpg)

**Comment by waldoj** [comment]
Whoa:

```
<section_number>
____________APP_A__________ORD_CRE_MUN</section_number>
```

Where are the `_`s coming from? Is that XML the XML that's being imported?

**Comment by krues8dr** [comment]
They've got a translation script from Municode's data format, I'm not altogether sure why those `_` are in there though.

**Comment by waldoj** [comment]
That definitely complicates things, because of course `trim()` won't touch 'em.

**Comment by krues8dr** [comment]
[Oh.](https://github.com/Code-for-Miami/statedecoded-parser/blob/master/xml-parser.rb#L56)

**Comment by waldoj** [comment]
Ahhh.

**Comment by krues8dr** [comment]
You can, btw, give `trim()` a `$character_mask` and add characters to it.

**Comment by waldoj** [comment]
![200_s](https://cloud.githubusercontent.com/assets/656758/8240046/f092ec2a-15cd-11e5-94d7-05c0ec1c7154.gif)

**Comment by waldoj** [comment]
So we're not trimming these, because we don't trim _any_ of the input from the XML. One way to handle this is to walk the object and trim every field, but that seems like a mistake, since some fields might _need_ whitespace, yeah? OTOH, XML can be a hell of a mess, and is often full of whitespace, like such:

```
<section>
123.45
</section>
```

I think this is probably best handled within the XSLT, which has its own ability to figure out how to handle whitespace during the transformation process. That way, people can make their own decision about what gets trimmed and what doesn't.

**Comment by krues8dr** [comment]
I _think_ there's no longer any XSLT, so this would be an extra step to do it that way.

**Comment by waldoj** [comment]
In practice, everybody's likely to need XSLT to get their XML in the State Decoded schema. (Or, of course, they could customize `Parser` and get it by hand.) All we've ever done with XSLT is packaged a sample file that they could use at the command line to get their XML in the right format.

**Comment by krues8dr** [comment]
I think you're conflating the import process - which has never used XSLT - with the process of getting the data into Solr - which did use XSLT and no longer does?

**Comment by waldoj** [comment]
Nope. The import process imports XML. The XML needs to be in the State Decoded format. So how does the XML come to be in the State Decoded format? Well, that occurs before our pipeline starts, but they use XSLT, probably, since that's the most reasonable way to convert XML from one schema to another. [That's what the sample XSLT file is for](https://github.com/statedecoded/statedecoded/blob/master/sample.xsl)—to show people how to do that.

How are _you_ turning provided third-party XML into one that validates against the State Decoded schema?

**Comment by krues8dr** [comment]
I've never even seen that file.  I thought you mean [the one I've spent the most time with](https://github.com/statedecoded/statedecoded/blob/master/solr_home/statedecoded/conf/xslt/stateDecodedXml.xsl).  We're using PHP parsers build on top of the default one which are schema-specific, thus the [American Legal parser](https://github.com/statedecoded/statedecoded/blob/master/includes/class.AmericanLegal.inc.php), etc.  Having to use multiple languages to do this work got really unscalable for us quick.

**Comment by waldoj** [comment]
That's why the custom parser option exists—different strokes for different folks. [That file was added in v0.8](http://www.statedecoded.com/2013/11/release-v08/), a release that you did a huge amount of the work for. :) For folks who are good with XSLT—and I'm learning—it's a really, really fast way to transmute XML formats.

Anyway, if you're using a custom parser, that seems like the place for this trimming to occur.

**Comment by krues8dr** [comment]
:+1:
