### ISSUE TITLE
Admin logging doesn't include carriage returns

### ISSUE THREAD

**Issue by waldoj** [statedecoded/statedecoded#688]
The iframe contents, containing output from the parser, look like such:

![output](https://cloud.githubusercontent.com/assets/656758/23883867/0734b830-0840-11e7-8672-207d470e265a.png)

The source looks like such:

![html](https://cloud.githubusercontent.com/assets/656758/23883875/09179cc6-0840-11e7-88f6-a55342fc5e4c.png)

Format this so that the output has carriage returns in the browser.

**Comment by krues8dr** [comment]
`laws_structure` is a foreign key introduced in the very first migration, `201402141654480001` – so I'm not sure why your database is mysteriously missing it?

**Comment by krues8dr** [comment]
It *should* be – are you updated to the latest version?  It's running `nl2br` on the output of the MigrateAction class, so these should have linebreaks.  

If this isn't working, the fix here is to use the Logger inside of MigrateAction instead of just printing newlines; the Logger can handle plain text or html, depending on the options it's passed.

**Comment by waldoj** [comment]
I think something weird was resulting from me having, unwittingly, an old version of the database, with a new version of the codebase. After blowing away the DB and having it create a new one, all is well. I can't see how this would have resulted from that, but here we are.
